// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/smurdoch/go-rest-api/src/api/app"
	"github.com/smurdoch/go-rest-api/src/api/controllers"
	"github.com/smurdoch/go-rest-api/src/api/repositories"
	"github.com/smurdoch/go-rest-api/src/api/services"
)

// Injectors from wire.go:

func InitializeApp() app.App {
	statusController := controllers.NewStatusController()
	admissionRepository := repositories.NewAdmissionRepository()
	admissionService := services.NewAdmissionService(admissionRepository)
	admissionController := controllers.NewAdmissionController(admissionService)
	appApp := app.New(statusController, admissionController)
	return appApp
}
